### ISSUE TITLE
[RFD] Query-based routing.

### ISSUE THREAD

**Issue by mskarbek** [levkk/pgcat#4]
This is more of a discussion topic then issue, but discussions are disabled, so here we are. :)
Interesting (at least for me) functionality would be an ability to route queries to separate read traffic from write. Simple use case: I have one master and two replicas, all write queries, no matter the client, should go to the master and all the rest to replicas.
Is this something worth considering?

**Comment by levkk** [comment]
Hey! Yes absolutely, that's a great suggestion, I've been thinking about it as well.

There are caveats and the implementation has to be pretty careful. I've seen other poolers, e.g. [Makara](https://github.com/instacart/makara), attempt to parse the SQL and figure out if it's a `SELECT` (read-only) or something else, e.g. `UPDATE`, `INSERT`, etc. That approach in practice is okay, up until you hit something like this:

```sql
SELECT some_mutating_function();
```.

This will get routed to a replica and we'll get an error back about the database being read-only.

An example where they don't attempt this at all is Rails 6, where they just make it explicit: the user has to pick a database for each query, since they are the best person to know if they are read-only or not.

These are corner cases though. I think in practice, we can come up with an approach that works 99% of the time and it can be customizable too.

**Comment by mskarbek** [comment]
I'm perfectly aware that this is not a trivial functionality. The ideal situation would be to require from developer separation on the application level, but that is not always possible. One way to approach this currently would be to monitor all application queries, verify edge cases, and hand pick a list for pgBouncer query routing. This is not ideal but serves its purpose in some number of cases and helps to deal with legacy applications. The question is how to improve upon that in a safe, reliable way, and is it worth the effort?

**Comment by ben-pr-p** [comment]
I think the way AWS's pg-bouncer-rr approaches it is pretty ideal: https://github.com/awslabs/pgbouncer-rr-patch

The only issue with their approach is that you can't access the parameter values: https://github.com/awslabs/pgbouncer-rr-patch/issues/47

Given that this is a Rust project and there is really good support for Rust / Javascript / Wasm interfaces from Deno, Wasmer, etc., I think it'd be most useful to be able to write your `route_query(username, query, parameters)` function in Javascript / wasm

I just discovered this project today from Postgres Weekly, but we've been considering patching `pgbouncer-rr` to fix the parameter issue because it solves such an important business use case for us, and so if there was anything we could do to help this along we'd love to!

**Comment by Faridalim** [comment]
Hi, awesome project. I think user choosing database is the easiest and clear implementation. Or maybe user need to add info on the query as "Read" or "Write" queries using SET

**Comment by levkk** [comment]
Hey @ben-pr-p , thanks for taking a look! #5 isn't quite done yet, but I see what you're saying. My plan was to start with explicit query routing and then slowly graduate to automatic query routing based on a regex or maybe something more complex.

That being said, if you'd like to give this a shot, I'd always welcome a PR :)

Thanks!

**Comment by davidfetter** [comment]
The only way you can actually know whether a query is actually going to cause a write is to plan it and look for nodes that write. There isn't some kind of clever inspection of the query text that can actually provide this information because the information may be in, for example, a rewrite rule which exists only on the DB side.

This is totally worth doing, but the cost is a round trip that grabs the plan tree and maybe some caching of query write-ness results. Of course, caching brings in one of the `Two Hard Problems of Computer Science`: Cache Invalidation. The other two are Naming Things and Off-By-One.

Anyhow, the point here is that if you attempt to be save labor by doing anything but ask the DB in question whether a write will occur, you will quickly find yourself in a tar pit.

**Comment by levkk** [comment]
@mskarbek I've added a basic query parser using `sqlparser` ([crate](https://docs.rs/sqlparser/latest/sqlparser/ast/index.html)). It's more advanced than a simple regex, because it'll be able to detect contexts like `WITH ...`, but it still may give false negatives for mutative `SELECT`s. That being said, this should cover 99% of use cases. It's disabled by default, just to make sure the caveats of using it are considered.
