### ISSUE TITLE
support caseless keyword like general pg does

### ISSUE THREAD

**Issue by DeoLeung** [levkk/pgcat#81]
**Is your feature request related to a problem? Please describe.**
```sql
-- this used to work, which I got some error describe in another issue
SET shard TO '2';

-- this not working
-- ERROR:  unrecognized configuration parameter "shard"
SET shard TO '1';

-- this works
SET SHARD TO '1';
```

**Describe the solution you'd like**

make this sql keyword caseless

**Comment by levkk** [comment]
They are already case-insensitive. Take a look at the regexes defined in `query_router.rs`, you'll note the `(?i)` [notation](https://stackoverflow.com/a/50271550/3478959). I think you might be on some old version of pgcat because I remember making them case-insensitive at some point. Try `git pull origin main` to update to latest version. Feel free to re-open if the bug re-occurs.

I think the issue you're facing is you're running the pooler in session mode and/or you're executing the `SET SHARD` command inside a transaction that's already assigned to a shard.

**Comment by DeoLeung** [comment]
I'm building from your #79 branch so it shall be up2date.

you're right, I got this error when I type the sql in my postico query IDE, if i did it from `psql` terminal, it works.

**Comment by levkk** [comment]
My guess Postico opens a transaction for you automatically. Once you're inside a transaction, you can't select a shard anymore because transactions have to run on a shard as soon as they are started and pgcat picks shard 0 by default in that case.
